### ISSUE TITLE
Bg Hover not working

### ISSUE THREAD

**Issue by lassev05** [lassev05/HypeStyle#2]
When you try to you use this class `bg-hover-COLOR_HERE` its not working!

We will fix this very soon!

**Comment by Shaurya-dub** [comment]
Hi there, sorry if this is a silly question as I'm still new to this. I'm interested in trying to fix the issue, but I'm unable to find the bg-hover class in any of the scss files.  Could you please point me towards where the class is defined so I can take a crack at the issue? Thank you

**Comment by lassev05** [comment]
Hi, I wrote this error to tell people it does not work: joy: But you are more than welcome to participate in the project and fix the error! Write to my email: vestergaardlasse2@gmail.com if you are interested

**Comment by lassev05** [comment]
> Hi there, sorry if this is a silly question as I'm still new to this. I'm interested in trying to fix the issue, but I'm unable to find the bg-hover class in any of the scss files. Could you please point me towards where the class is defined so I can take a crack at the issue? Thank you

Hi, I wrote this error to tell people it does not work 😂  But you are more than welcome to participate in the project and fix the error! Write to my email: vestergaardlasse2@gmail.com if you are interested
